import './globals.css';
import Topbar from './Topbar';

import styles from './rootLayout.module.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main className="flex min-h-screen flex-col">
          <Topbar />
          <div
            className={`relative min-h-screen p-12 ${styles.dotBackground}`}
          >
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
